export enum Statuses {
  NEW = 'NEW',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  WAITING_FOR_CONFIRMATION = 'WAITING_FOR_CONFIRMATION',
  IN_PROGRESS = 'IN_PROGRESS',
  TO_BE_SHIPPED = 'TO_BE_SHIPPED',
  SHIPPING = 'SHIPPING',
  DELIVERED = 'DELIVERED',
  DONE = 'DONE',
}
