const vegatables = [
  {
    name: 'Avocado',
    description: 'Świeże avocado',
    price: 6.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/avocado.png',
  },
  {
    name: 'Bakłażan',
    description: 'Świeży bakłażan',
    price: 3.9,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/baklazan.png',
  },
  {
    name: 'Bataty',
    description: 'Świeże bataty',
    price: 5.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/bataty.png',
  },
  {
    name: 'Bób',
    description: 'Świeży bób',
    price: 28.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/bob.png',
  },
  {
    name: 'Botwinka',
    description: 'Świeża botwinka',
    price: 7.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/botwinka.png',
  },
  {
    name: 'Brokuł',
    description: 'Świeży brokuł',
    price: 8.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/brokul.png',
  },
  {
    name: 'Brukselka',
    description: 'Świeża brukselka',
    price: 14.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/brukselka.png',
  },
  {
    name: 'Burak',
    description: 'Świeży burak',
    price: 3.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/burak.png',
  },
  {
    name: 'Cebula biała',
    description: 'Świeża cebula biała',
    price: 3.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/cebulabiala.png',
  },
  {
    name: 'Cebula czerwona',
    description: 'Świeża cebula czerwona',
    price: 6.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/cebulaczerwona.jpeg',
  },
  {
    name: 'Cukinia',
    description: 'Świeża cukinia',
    price: 5.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/cukinia.jpeg',
  },
  {
    name: 'Czosnek główka',
    description: 'Świeży czosnek główka',
    price: 2.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/czosnek.png',
  },
  {
    name: 'Dynia',
    description: 'Świeża dynia',
    price: 10.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/dynia.png',
  },
  {
    name: 'Fasolka szparagowa',
    description: 'Świeża fasolka szparagowa',
    price: 15.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/fasolkaszparagowa.jpg',
  },
  {
    name: 'Imbir',
    description: 'Świeży imbir',
    price: 30.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/imbir.jpeg',
  },
  {
    name: 'Kalafior',
    description: 'Świeży kalafior',
    price: 12.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/kalafior.png',
  },
  {
    name: 'Kapusta biała',
    description: 'Świeża kapusta biała',
    price: 5.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/kapustabiala.png',
  },
  {
    name: 'Kapusta czerwona',
    description: 'Świeża kapusta czerwona',
    price: 7.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/kapustaczerwona.png',
  },
  {
    name: 'Koper',
    description: 'Świeży koper',
    price: 2.7,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/koper.jpeg',
  },
  {
    name: 'Marchew',
    description: 'Świeża marchew',
    price: 4.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/marchew.png',
  },
  {
    name: 'Ogórek gruntowy',
    description: 'Świeży ogórek gruntowy',
    price: 6.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/ogorek.jpeg',
  },
  {
    name: 'Papryka',
    description: 'Świeża papryka',
    price: 18.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/papryka.jpg',
  },
  {
    name: 'Pieczarka',
    description: 'Świeża pieczarka',
    price: 12.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/pieczarka.jpeg',
  },
  {
    name: 'Pomidor malinowy',
    description: 'Świeży pomidor malinowy',
    price: 23.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/pomidor.jpg',
  },
  {
    name: 'Pomidor Polski',
    description: 'Świeży pomidor polski',
    price: 15.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/pomidor1.jpg',
  },
  {
    name: 'Por',
    description: 'Świeży por',
    price: 5.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/por.jpeg',
  },
  {
    name: 'Rabarbar',
    description: 'Świeży rabarbar',
    price: 12.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/rabarbar.jpeg',
  },
  {
    name: 'Roszponka',
    description: 'Świeża roszponka',
    price: 6.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/roszponka.jpeg',
  },
  {
    name: 'Rukola',
    description: 'Świeża rukola',
    price: 6.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/rukola.jpeg',
  },
  {
    name: 'Rzodkiewka pęczek',
    description: 'Świeża rzodkiewka pęczek',
    price: 3.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/rzodkiewka.png',
  },
  {
    name: 'Sałata lodowa',
    description: 'Świeża sałata lodowa',
    price: 6.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/salatalodowa.jpeg',
  },
  {
    name: 'Sałata masłowa',
    description: 'Świeża sałata masłowa',
    price: 5.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/salata.jpeg',
  },
  {
    name: 'Sałata rzymska',
    description: 'Świeża sałata rzymska',
    price: 7.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/salata1.jpeg',
  },
  {
    name: 'Sałata strzępiasta',
    description: 'Świeża sałata strzępiasta',
    price: 5.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/salata2.jpeg',
  },
  {
    name: 'Seler korzeń',
    description: 'Świeży seler korzeń',
    price: 6.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/seler.png',
  },
  {
    name: 'Seler naciowy',
    description: 'Świeży seler naciowy',
    price: 6.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/selernaciowy.jpg',
  },
  {
    name: 'Szczypiorek',
    description: 'Świeży szczypiorek',
    price: 2.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/szczypiorek.png',
  },
  {
    name: 'Szparagi',
    description: 'Świeże szparagi',
    price: 35.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/szparagi.jpg',
  },
  {
    name: 'Szpinak świeży',
    description: 'Świeży szpinak',
    price: 8.0,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/szpinak.jpeg',
  },
  {
    name: 'Ziemniak żółty',
    description: 'Świeży ziemniak żółty',
    price: 2.5,
    category: 'warzywa',
    stock_quantity: 100,
    image: 'uploads/ziemniak.jpeg',
  },
];

export default vegatables;
